language: python
python:
 - "3.6"
cache: pip
services:
 - postgresql
install:
 - pip install -r requirements.txt
before_script:
 - psql -c 'create database teststore;' -U postgres
script:
 - pytest -v --cov=app
after_script:
 - coveralls 
after_success:
- coveralls